import { PlaceHolderImages } from "./placeholder-images";

export const NAV_LINKS = [
  { href: '/', label: 'Home' },
  { href: '/properties', label: 'Properties' },
  { href: '/dakhla', label: 'Why Dakhla' },
  { href: '/about', label: 'About' },
  { href: '/contact', label: 'Contact' },
];

export const MOCK_PROPERTIES = [
  {
    id: 'p1',
    title: 'Oceanfront Oasis',
    price: 350000,
    size: 5000,
    location: 'Coastal',
    description: 'A stunning plot with direct access to the beach, perfect for a luxury villa or a boutique hotel. Unobstructed views of the Atlantic. This premium location offers a unique blend of tranquility and accessibility, making it a prime investment for high-end residential or hospitality development.',
    image: PlaceHolderImages.find(p => p.id === 'property-2'),
    latitude: 23.706,
    longitude: -15.93,
    features: ['Direct Beach Access', 'Ocean Views', 'Prime for Tourism', 'Utilities Ready'],
  },
  {
    id: 'p2',
    title: 'The Entrepreneur\'s Expanse',
    price: 180000,
    size: 10000,
    location: 'Inland',
    description: 'A vast expanse of flat land ideal for large-scale commercial or agricultural projects. Close to main transport routes, this plot is a strategic asset for ventures requiring space and logistical efficiency, such as large-scale farming, solar energy plants, or industrial parks.',
    image: PlaceHolderImages.find(p => p.id === 'property-1'),
    latitude: 23.75,
    longitude: -15.8,
    features: ['Large Scale', 'Flat Topography', 'Logistical Hub Access', 'High Potential ROI'],
  },
  {
    id: 'p3',
    title: 'Lagoon View Lot',
    price: 275000,
    size: 4500,
    location: 'Coastal',
    description: 'Overlooking the serene Dakhla lagoon, this plot is a haven for water sports enthusiasts and those seeking tranquility. It is an exceptional spot for a personal villa or a kitesurfing camp, capitalizing on Dakhla\'s reputation as a world-class destination.',
    image: PlaceHolderImages.find(p => p.id === 'property-5'),
    latitude: 23.79,
    longitude: -15.90,
    features: ['Lagoon View', 'Kitesurfing Hotspot', 'Tourism Potential', 'Peaceful Environment'],
  },
  {
    id: 'p4',
    title: 'Strategic Industrial Plot',
    price: 220000,
    size: 20000,
    location: 'Industrial',
    description: 'Located in the new industrial zone near the Dakhla Atlantic Port project, this plot is perfect for logistics, manufacturing, or warehousing. Its strategic position offers a significant advantage for businesses looking to tap into the new trade routes.',
    image: PlaceHolderImages.find(p => p.id === 'property-3'),
    latitude: 23.85,
    longitude: -15.75,
    features: ['Industrial Zone', 'Port Proximity', 'Large Surface Area', 'Infrastructure Ready'],
  },
  {
    id: 'p5',
    title: 'Desert Rose Retreat',
    price: 120000,
    size: 8000,
    location: 'Inland',
    description: 'A secluded and peaceful lot surrounded by unique desert landscapes. Ideal for a private retreat, a luxury desert camp, or an eco-tourism project focusing on stargazing and unique desert experiences. Away from the city buzz but accessible.',
    image: PlaceHolderImages.find(p => p.id === 'property-4'),
    latitude: 23.6,
    longitude: -15.85,
    features: ['Secluded', 'Eco-Tourism Ready', 'Unique Landscape', 'Starry Nights'],
  },
  {
    id: 'p6',
    title: 'Prime Commercial Corner',
    price: 450000,
    size: 3000,
    location: 'Urban',
    description: 'A high-visibility plot at a major intersection in the growing urban center of Dakhla. Suitable for retail, a shopping center, or a mixed-use development, this location guarantees high footfall and commercial success.',
    image: PlaceHolderImages.find(p => p.id === 'property-6'),
    latitude: 23.71,
    longitude: -15.945,
    features: ['High Visibility', 'Urban Center', 'Commercial Zoning', 'Rapid Growth Area'],
  },
];

export type Property = (typeof MOCK_PROPERTIES)[0];
